name       : python-logilab-common
version    : 1.4.1
release    : 3
source     :
    - https://pypi.python.org/packages/5b/ad/a4020c78d0bf3bacf7f039176943367f912700221160c180c74346aa6c4a/logilab-common-1.4.1.tar.gz : ed1c60f32c3fa03dc2efaa730e606db1209d14b4769561ff0365aa584a29360a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.python
summary    : Collection of low-level Python packages and modules used by Logilab projects
description: |
    Collection of low-level Python packages and modules used by Logilab projects
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
